/**
 * Model definitions for the native registry (Part 1)
 *
 * Categories: text_to_video, image_to_video, image_to_image
 * Ported from packages/video-agent-skill registry_data.py
 *
 * @module electron/native-pipeline/registry-data
 */

import { ModelRegistry } from "./registry.js";

export function registerTextToVideoModels(): void {
	ModelRegistry.register({
		key: "hailuo_pro",
		name: "MiniMax Hailuo-02 Pro",
		provider: "MiniMax",
		endpoint: "fal-ai/minimax/hailuo-02/pro/text-to-video",
		categories: ["text_to_video"],
		description: "Cost-effective text-to-video with prompt optimization",
		pricing: { type: "per_video", cost: 0.08 },
		durationOptions: ["6"],
		aspectRatios: ["16:9"],
		resolutions: ["1080p"],
		defaults: { prompt_optimizer: true },
		features: ["prompt_optimizer", "1080p", "cost_effective"],
		maxDuration: 6,
		costEstimate: 0.08,
		processingTime: 60,
	});

	ModelRegistry.register({
		key: "veo3",
		name: "Google Veo 3",
		provider: "Google (via FAL)",
		endpoint: "fal-ai/veo3",
		categories: ["text_to_video"],
		description: "Premium quality with audio generation",
		pricing: { type: "per_second", cost_no_audio: 0.5, cost_with_audio: 0.75 },
		durationOptions: ["5s", "6s", "7s", "8s"],
		aspectRatios: ["16:9", "9:16", "1:1"],
		resolutions: ["720p"],
		defaults: {
			duration: "8s",
			aspect_ratio: "16:9",
			generate_audio: true,
			enhance_prompt: true,
		},
		features: [
			"audio_generation",
			"enhance_prompt",
			"negative_prompt",
			"seed_control",
		],
		maxDuration: 8,
		costEstimate: 4.0,
		processingTime: 300,
	});

	ModelRegistry.register({
		key: "veo3_fast",
		name: "Google Veo 3 Fast",
		provider: "Google (via FAL)",
		endpoint: "fal-ai/veo3/fast",
		categories: ["text_to_video"],
		description: "Fast generation with good quality",
		pricing: { type: "per_second", cost_no_audio: 0.25, cost_with_audio: 0.4 },
		durationOptions: ["5s", "6s", "7s", "8s"],
		aspectRatios: ["16:9", "9:16", "1:1"],
		resolutions: ["720p"],
		defaults: { duration: "8s", aspect_ratio: "16:9", generate_audio: true },
		features: ["audio_generation", "fast_processing", "seed_control"],
		maxDuration: 8,
		costEstimate: 2.0,
		processingTime: 120,
	});

	ModelRegistry.register({
		key: "kling_2_6_pro",
		name: "Kling Video v2.6 Pro",
		provider: "Kuaishou",
		endpoint: "fal-ai/kling-video/v2.6/pro/text-to-video",
		categories: ["text_to_video"],
		description: "Professional text-to-video with audio support",
		pricing: { type: "per_second", cost_no_audio: 0.07, cost_with_audio: 0.14 },
		durationOptions: ["5", "10"],
		aspectRatios: ["16:9", "9:16", "1:1"],
		resolutions: ["720p"],
		defaults: {
			duration: "5",
			aspect_ratio: "16:9",
			negative_prompt: "blur, distort, and low quality",
			cfg_scale: 0.5,
			generate_audio: true,
		},
		features: [
			"audio_generation",
			"negative_prompt",
			"cfg_scale",
			"multilingual",
		],
		maxDuration: 10,
		costEstimate: 0.35,
		processingTime: 90,
	});

	ModelRegistry.register({
		key: "kling_3_standard",
		name: "Kling Video v3 Standard",
		provider: "Kuaishou",
		endpoint: "fal-ai/kling-video/v3/standard/text-to-video",
		categories: ["text_to_video"],
		description:
			"Latest generation with native audio, voice control, and multi-prompt support",
		pricing: {
			type: "per_second",
			cost_no_audio: 0.168,
			cost_with_audio: 0.252,
			cost_voice_control: 0.308,
		},
		durationOptions: [
			"3",
			"4",
			"5",
			"6",
			"7",
			"8",
			"9",
			"10",
			"11",
			"12",
			"13",
			"14",
			"15",
		],
		aspectRatios: ["16:9", "9:16", "1:1"],
		resolutions: ["720p"],
		defaults: {
			duration: "5",
			aspect_ratio: "16:9",
			negative_prompt: "blur, distort, and low quality",
			cfg_scale: 0.5,
			generate_audio: false,
			voice_ids: [],
			multi_prompt: [],
			shot_type: null,
		},
		features: [
			"audio_generation",
			"voice_control",
			"multi_prompt",
			"shot_type",
			"negative_prompt",
			"cfg_scale",
			"multilingual",
		],
		maxDuration: 12,
		costEstimate: 0.84,
		processingTime: 90,
	});

	ModelRegistry.register({
		key: "kling_3_pro",
		name: "Kling Video v3 Pro",
		provider: "Kuaishou",
		endpoint: "fal-ai/kling-video/v3/pro/text-to-video",
		categories: ["text_to_video"],
		description:
			"Top-tier cinematic visuals with native audio, voice control, and multi-prompt support",
		pricing: {
			type: "per_second",
			cost_no_audio: 0.224,
			cost_with_audio: 0.336,
			cost_voice_control: 0.392,
		},
		durationOptions: [
			"3",
			"4",
			"5",
			"6",
			"7",
			"8",
			"9",
			"10",
			"11",
			"12",
			"13",
			"14",
			"15",
		],
		aspectRatios: ["16:9", "9:16", "1:1"],
		resolutions: ["720p"],
		defaults: {
			duration: "5",
			aspect_ratio: "16:9",
			negative_prompt: "blur, distort, and low quality",
			cfg_scale: 0.5,
			generate_audio: false,
			voice_ids: [],
			multi_prompt: [],
			shot_type: null,
		},
		features: [
			"audio_generation",
			"voice_control",
			"multi_prompt",
			"shot_type",
			"negative_prompt",
			"cfg_scale",
			"multilingual",
			"professional_quality",
		],
		maxDuration: 12,
		costEstimate: 1.12,
		processingTime: 90,
	});

	ModelRegistry.register({
		key: "kling_o3_pro_t2v",
		name: "Kling O3 Pro Text-to-Video",
		provider: "Kuaishou",
		endpoint: "fal-ai/kling-video/o3/pro/text-to-video",
		categories: ["text_to_video"],
		description:
			"O3 (Omni) model with element-based character/object consistency and @ reference syntax",
		pricing: {
			type: "per_second",
			cost_no_audio: 0.224,
			cost_with_audio: 0.28,
		},
		durationOptions: ["3", "5", "10", "15"],
		aspectRatios: ["16:9", "9:16", "1:1"],
		resolutions: ["720p", "1080p"],
		defaults: {
			duration: "5",
			aspect_ratio: "16:9",
			negative_prompt: null,
			cfg_scale: 0.5,
			generate_audio: true,
			elements: [],
			image_urls: [],
			multi_prompt: [],
			shot_type: null,
		},
		features: [
			"audio_generation",
			"elements",
			"reference_images",
			"reference_syntax",
			"multi_prompt",
			"shot_type",
			"negative_prompt",
			"cfg_scale",
			"professional_quality",
		],
		maxDuration: 15,
		costEstimate: 1.12,
		processingTime: 90,
	});

	ModelRegistry.register({
		key: "sora_2",
		name: "Sora 2",
		provider: "OpenAI (via FAL)",
		endpoint: "fal-ai/sora-2/text-to-video",
		categories: ["text_to_video"],
		description: "OpenAI's text-to-video model",
		pricing: { type: "per_second", cost: 0.1 },
		durationOptions: [4, 8, 12],
		aspectRatios: ["16:9", "9:16"],
		resolutions: ["720p"],
		defaults: {
			duration: 4,
			resolution: "720p",
			aspect_ratio: "16:9",
			delete_video: true,
		},
		features: ["aspect_ratio", "long_duration"],
		maxDuration: 12,
		costEstimate: 0.4,
		processingTime: 120,
	});

	ModelRegistry.register({
		key: "sora_2_pro",
		name: "Sora 2 Pro",
		provider: "OpenAI (via FAL)",
		endpoint: "fal-ai/sora-2/text-to-video/pro",
		categories: ["text_to_video"],
		description: "Professional Sora with 1080p support",
		pricing: { type: "per_second", cost_720p: 0.3, cost_1080p: 0.5 },
		durationOptions: [4, 8, 12],
		aspectRatios: ["16:9", "9:16"],
		resolutions: ["720p", "1080p"],
		defaults: {
			duration: 4,
			resolution: "1080p",
			aspect_ratio: "16:9",
			delete_video: true,
		},
		features: ["aspect_ratio", "1080p", "long_duration"],
		maxDuration: 12,
		costEstimate: 2.0,
		processingTime: 180,
	});

	ModelRegistry.register({
		key: "grok_imagine",
		name: "xAI Grok Imagine Video",
		provider: "xAI (via FAL)",
		endpoint: "xai/grok-imagine-video/text-to-video",
		categories: ["text_to_video"],
		description: "xAI's text-to-video with native audio generation",
		pricing: {
			type: "per_second",
			base_duration: 6,
			base_cost_6s: 0.3,
			cost_per_additional_second: 0.05,
		},
		durationOptions: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
		aspectRatios: ["16:9", "4:3", "3:2", "1:1", "2:3", "3:4", "9:16"],
		resolutions: ["480p", "720p"],
		defaults: { duration: 6, resolution: "720p", aspect_ratio: "16:9" },
		features: [
			"audio_generation",
			"flexible_duration",
			"multiple_aspect_ratios",
		],
		maxDuration: 15,
		costEstimate: 0.3,
		processingTime: 60,
	});
}

export function registerImageToVideoModels(): void {
	ModelRegistry.register({
		key: "hailuo",
		name: "MiniMax Hailuo-02",
		provider: "MiniMax",
		endpoint: "fal-ai/minimax/hailuo-02/standard/image-to-video",
		categories: ["image_to_video"],
		description: "Standard image-to-video with prompt optimization",
		pricing: 0.05,
		durationOptions: ["6", "10"],
		resolutions: ["768p"],
		defaults: { duration: "6", prompt_optimizer: true },
		features: ["prompt_optimizer"],
		maxDuration: 10,
		extendedParams: ["start_frame"],
		extendedFeatures: {
			start_frame: true,
			end_frame: false,
			ref_images: false,
			audio_input: false,
			audio_generate: false,
			ref_video: false,
		},
		costEstimate: 0.08,
		processingTime: 60,
	});

	ModelRegistry.register({
		key: "kling_2_1",
		name: "Kling Video v2.1",
		provider: "Kuaishou",
		endpoint: "fal-ai/kling-video/v2.1/standard/image-to-video",
		categories: ["image_to_video"],
		description:
			"High-quality generation with negative prompts and frame interpolation",
		pricing: 0.05,
		durationOptions: ["5", "10"],
		resolutions: ["720p", "1080p"],
		defaults: {
			duration: "5",
			negative_prompt: "blur, distort, and low quality",
			cfg_scale: 0.5,
		},
		features: ["negative_prompt", "cfg_scale", "frame_interpolation"],
		maxDuration: 10,
		extendedParams: ["start_frame", "end_frame"],
		extendedFeatures: {
			start_frame: true,
			end_frame: true,
			ref_images: false,
			audio_input: false,
			audio_generate: false,
			ref_video: false,
		},
		costEstimate: 0.5,
		processingTime: 90,
	});

	ModelRegistry.register({
		key: "kling_2_6_pro_i2v",
		name: "Kling Video v2.6 Pro",
		provider: "Kuaishou",
		endpoint: "fal-ai/kling-video/v2.6/pro/image-to-video",
		categories: ["image_to_video"],
		providerKey: "kling_2_6_pro",
		description:
			"Professional tier with enhanced quality and frame interpolation",
		pricing: 0.1,
		durationOptions: ["5", "10"],
		resolutions: ["720p", "1080p"],
		defaults: {
			duration: "5",
			negative_prompt: "blur, distort, and low quality",
			cfg_scale: 0.5,
		},
		features: [
			"negative_prompt",
			"cfg_scale",
			"professional_quality",
			"frame_interpolation",
		],
		maxDuration: 10,
		extendedParams: ["start_frame", "end_frame"],
		extendedFeatures: {
			start_frame: true,
			end_frame: true,
			ref_images: false,
			audio_input: false,
			audio_generate: false,
			ref_video: false,
		},
		costEstimate: 1.0,
		processingTime: 120,
	});

	ModelRegistry.register({
		key: "kling_3_standard_i2v",
		name: "Kling Video v3 Standard",
		provider: "Kuaishou",
		endpoint: "fal-ai/kling-video/v3/standard/image-to-video",
		categories: ["image_to_video"],
		providerKey: "kling_3_standard",
		description:
			"Latest generation with native audio, voice control, and multi-prompt support",
		pricing: { no_audio: 0.168, audio: 0.252, voice_control: 0.308 },
		durationOptions: ["5", "10", "12"],
		aspectRatios: ["16:9", "9:16", "1:1"],
		resolutions: ["720p", "1080p"],
		defaults: {
			duration: "5",
			negative_prompt: "blur, distort, and low quality",
			cfg_scale: 0.5,
			generate_audio: false,
			voice_ids: [],
			multi_prompt: [],
			elements: [],
			aspect_ratio: "16:9",
		},
		features: [
			"negative_prompt",
			"cfg_scale",
			"frame_interpolation",
			"audio_generation",
			"voice_control",
			"multi_prompt",
			"custom_elements",
		],
		maxDuration: 12,
		extendedParams: ["start_frame", "end_frame", "audio_generate", "elements"],
		extendedFeatures: {
			start_frame: true,
			end_frame: true,
			ref_images: true,
			audio_input: false,
			audio_generate: true,
			ref_video: true,
		},
		costEstimate: 0.84,
		processingTime: 90,
	});

	ModelRegistry.register({
		key: "kling_3_pro_i2v",
		name: "Kling Video v3 Pro",
		provider: "Kuaishou",
		endpoint: "fal-ai/kling-video/v3/pro/image-to-video",
		categories: ["image_to_video"],
		providerKey: "kling_3_pro",
		description:
			"Top-tier cinematic visuals with native audio, voice control, and multi-prompt support",
		pricing: { no_audio: 0.224, audio: 0.336, voice_control: 0.392 },
		durationOptions: ["5", "10", "12"],
		aspectRatios: ["16:9", "9:16", "1:1"],
		resolutions: ["720p", "1080p"],
		defaults: {
			duration: "5",
			negative_prompt: "blur, distort, and low quality",
			cfg_scale: 0.5,
			generate_audio: false,
			voice_ids: [],
			multi_prompt: [],
			elements: [],
			aspect_ratio: "16:9",
		},
		features: [
			"negative_prompt",
			"cfg_scale",
			"professional_quality",
			"frame_interpolation",
			"audio_generation",
			"voice_control",
			"multi_prompt",
			"custom_elements",
		],
		maxDuration: 12,
		extendedParams: ["start_frame", "end_frame", "audio_generate", "elements"],
		extendedFeatures: {
			start_frame: true,
			end_frame: true,
			ref_images: true,
			audio_input: false,
			audio_generate: true,
			ref_video: true,
		},
		costEstimate: 1.12,
		processingTime: 90,
	});

	ModelRegistry.register({
		key: "kling_o3_standard_i2v",
		name: "Kling O3 Standard Image-to-Video",
		provider: "Kuaishou",
		endpoint: "fal-ai/kling-video/o3/standard/image-to-video",
		categories: ["image_to_video"],
		description:
			"O3 (Omni) model with element-based character/object consistency",
		pricing: { no_audio: 0.168, audio: 0.224 },
		durationOptions: ["3", "5", "10", "15"],
		aspectRatios: ["16:9", "9:16", "1:1"],
		resolutions: ["720p", "1080p"],
		defaults: {
			duration: "5",
			generate_audio: true,
			elements: [],
			image_urls: [],
			aspect_ratio: "16:9",
			negative_prompt: null,
			cfg_scale: 0.5,
		},
		features: ["audio_generation", "elements", "end_frame", "reference_images"],
		maxDuration: 15,
		extendedParams: [
			"start_frame",
			"end_frame",
			"audio_generate",
			"elements",
			"image_urls",
		],
		extendedFeatures: {
			start_frame: true,
			end_frame: true,
			ref_images: true,
			audio_input: false,
			audio_generate: true,
			ref_video: false,
			elements: true,
		},
		costEstimate: 0.84,
		processingTime: 90,
	});

	ModelRegistry.register({
		key: "kling_o3_pro_i2v",
		name: "Kling O3 Pro Image-to-Video",
		provider: "Kuaishou",
		endpoint: "fal-ai/kling-video/o3/pro/image-to-video",
		categories: ["image_to_video"],
		description:
			"Professional O3 (Omni) model with enhanced quality and element consistency",
		pricing: { no_audio: 0.224, audio: 0.28 },
		durationOptions: ["3", "5", "10", "15"],
		aspectRatios: ["16:9", "9:16", "1:1"],
		resolutions: ["720p", "1080p"],
		defaults: {
			duration: "5",
			generate_audio: true,
			elements: [],
			image_urls: [],
			aspect_ratio: "16:9",
			negative_prompt: null,
			cfg_scale: 0.5,
		},
		features: [
			"audio_generation",
			"elements",
			"end_frame",
			"reference_images",
			"professional_quality",
		],
		maxDuration: 15,
		extendedParams: [
			"start_frame",
			"end_frame",
			"audio_generate",
			"elements",
			"image_urls",
		],
		extendedFeatures: {
			start_frame: true,
			end_frame: true,
			ref_images: true,
			audio_input: false,
			audio_generate: true,
			ref_video: false,
			elements: true,
		},
		costEstimate: 1.12,
		processingTime: 90,
	});

	ModelRegistry.register({
		key: "kling_o3_standard_ref",
		name: "Kling O3 Standard Reference-to-Video",
		provider: "Kuaishou",
		endpoint: "fal-ai/kling-video/o3/standard/reference-to-video",
		categories: ["image_to_video"],
		description:
			"O3 reference model with @ syntax for element-based character generation",
		pricing: { no_audio: 0.084, audio: 0.112 },
		durationOptions: ["3", "5", "10", "15"],
		aspectRatios: ["16:9", "9:16", "1:1"],
		resolutions: ["720p", "1080p"],
		defaults: {
			duration: "5",
			generate_audio: false,
			elements: [],
			image_urls: [],
			aspect_ratio: "16:9",
			multi_prompt: [],
			shot_type: null,
		},
		features: [
			"audio_generation",
			"elements",
			"reference_images",
			"reference_syntax",
			"multi_prompt",
		],
		maxDuration: 15,
		extendedParams: ["start_frame", "audio_generate", "elements", "image_urls"],
		extendedFeatures: {
			start_frame: true,
			end_frame: false,
			ref_images: true,
			audio_input: false,
			audio_generate: true,
			ref_video: false,
			elements: true,
		},
		costEstimate: 0.42,
		processingTime: 90,
	});

	ModelRegistry.register({
		key: "kling_o3_pro_ref",
		name: "Kling O3 Pro Reference-to-Video",
		provider: "Kuaishou",
		endpoint: "fal-ai/kling-video/o3/pro/reference-to-video",
		categories: ["image_to_video"],
		description:
			"Professional O3 reference model with @ syntax and enhanced quality",
		pricing: { no_audio: 0.224, audio: 0.28 },
		durationOptions: ["3", "5", "10", "15"],
		aspectRatios: ["16:9", "9:16", "1:1"],
		resolutions: ["720p", "1080p"],
		defaults: {
			duration: "5",
			generate_audio: false,
			elements: [],
			image_urls: [],
			aspect_ratio: "16:9",
		},
		features: [
			"audio_generation",
			"elements",
			"end_frame",
			"reference_images",
			"reference_syntax",
			"professional_quality",
		],
		maxDuration: 15,
		extendedParams: [
			"start_frame",
			"end_frame",
			"audio_generate",
			"elements",
			"image_urls",
		],
		extendedFeatures: {
			start_frame: true,
			end_frame: true,
			ref_images: true,
			audio_input: false,
			audio_generate: true,
			ref_video: false,
			elements: true,
		},
		costEstimate: 1.12,
		processingTime: 90,
	});

	ModelRegistry.register({
		key: "seedance_1_5_pro",
		name: "ByteDance Seedance v1.5 Pro",
		provider: "ByteDance",
		endpoint: "fal-ai/bytedance/seedance/v1.5/pro/image-to-video",
		categories: ["image_to_video"],
		description: "Advanced motion synthesis with seed control",
		pricing: 0.08,
		durationOptions: ["5", "10"],
		resolutions: ["720p", "1080p"],
		defaults: { duration: "5", seed: null },
		features: ["seed_control", "motion_quality"],
		maxDuration: 10,
		extendedParams: ["start_frame"],
		extendedFeatures: {
			start_frame: true,
			end_frame: false,
			ref_images: false,
			audio_input: false,
			audio_generate: false,
			ref_video: false,
		},
		costEstimate: 0.8,
		processingTime: 90,
	});

	ModelRegistry.register({
		key: "sora_2_i2v",
		name: "Sora 2",
		provider: "OpenAI (via FAL)",
		endpoint: "fal-ai/sora-2/image-to-video",
		categories: ["image_to_video"],
		providerKey: "sora_2",
		description: "OpenAI's image-to-video model",
		pricing: 0.1,
		durationOptions: [4, 8, 12],
		aspectRatios: ["auto", "9:16", "16:9"],
		resolutions: ["auto", "720p"],
		defaults: {
			duration: 4,
			resolution: "auto",
			aspect_ratio: "auto",
			delete_video: true,
		},
		features: ["aspect_ratio", "resolution"],
		maxDuration: 12,
		extendedParams: ["start_frame"],
		extendedFeatures: {
			start_frame: true,
			end_frame: false,
			ref_images: false,
			audio_input: false,
			audio_generate: false,
			ref_video: false,
		},
		costEstimate: 0.4,
		processingTime: 120,
	});

	ModelRegistry.register({
		key: "sora_2_pro_i2v",
		name: "Sora 2 Pro",
		provider: "OpenAI (via FAL)",
		endpoint: "fal-ai/sora-2/image-to-video/pro",
		categories: ["image_to_video"],
		providerKey: "sora_2_pro",
		description: "Professional Sora with 1080p support",
		pricing: 0.3,
		durationOptions: [4, 8, 12],
		aspectRatios: ["auto", "9:16", "16:9"],
		resolutions: ["auto", "720p", "1080p"],
		defaults: {
			duration: 4,
			resolution: "auto",
			aspect_ratio: "auto",
			delete_video: true,
		},
		features: ["aspect_ratio", "resolution", "1080p"],
		maxDuration: 12,
		extendedParams: ["start_frame"],
		extendedFeatures: {
			start_frame: true,
			end_frame: false,
			ref_images: false,
			audio_input: false,
			audio_generate: false,
			ref_video: false,
		},
		costEstimate: 2.0,
		processingTime: 180,
	});

	ModelRegistry.register({
		key: "veo_3_1_fast",
		name: "Veo 3.1 Fast",
		provider: "Google (via FAL)",
		endpoint: "fal-ai/veo3.1/fast/image-to-video",
		categories: ["image_to_video"],
		description: "Fast video generation with optional audio",
		pricing: 0.1,
		durationOptions: ["4s", "6s", "8s"],
		aspectRatios: ["auto", "16:9", "9:16"],
		resolutions: ["720p", "1080p"],
		defaults: {
			duration: "8s",
			resolution: "720p",
			aspect_ratio: "auto",
			generate_audio: true,
			auto_fix: false,
		},
		features: ["audio_generation", "auto_fix", "fast_processing"],
		maxDuration: 8,
		extendedParams: ["start_frame", "audio_generate"],
		extendedFeatures: {
			start_frame: true,
			end_frame: false,
			ref_images: false,
			audio_input: false,
			audio_generate: true,
			ref_video: false,
		},
		costEstimate: 1.2,
		processingTime: 120,
	});

	ModelRegistry.register({
		key: "wan_2_6",
		name: "Wan v2.6",
		provider: "Wan",
		endpoint: "wan/v2.6/image-to-video",
		categories: ["image_to_video"],
		description: "High-quality image-to-video with multi-shot support",
		pricing: 0.1,
		durationOptions: ["5", "10", "15"],
		aspectRatios: ["16:9", "9:16", "1:1"],
		resolutions: ["720p", "1080p"],
		defaults: {
			duration: "5",
			resolution: "1080p",
			negative_prompt: "",
			enable_prompt_expansion: true,
			multi_shots: false,
			seed: null,
			enable_safety_checker: true,
		},
		features: [
			"prompt_expansion",
			"multi_shots",
			"audio_input",
			"seed_control",
			"safety_checker",
		],
		maxDuration: 15,
		extendedParams: ["start_frame", "audio_input"],
		extendedFeatures: {
			start_frame: true,
			end_frame: false,
			ref_images: false,
			audio_input: true,
			audio_generate: false,
			ref_video: false,
		},
		costEstimate: 0.5,
		processingTime: 90,
	});

	ModelRegistry.register({
		key: "grok_imagine_i2v",
		name: "xAI Grok Imagine Video",
		provider: "xAI (via FAL)",
		endpoint: "xai/grok-imagine-video/image-to-video",
		categories: ["image_to_video"],
		providerKey: "grok_imagine",
		description: "xAI's image-to-video with native audio generation",
		pricing: 0.05,
		durationOptions: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
		aspectRatios: ["auto", "16:9", "4:3", "3:2", "1:1", "2:3", "3:4", "9:16"],
		resolutions: ["480p", "720p"],
		defaults: { duration: 6, resolution: "720p", aspect_ratio: "auto" },
		features: [
			"audio_generation",
			"flexible_duration",
			"multiple_aspect_ratios",
		],
		maxDuration: 15,
		extendedParams: ["start_frame"],
		extendedFeatures: {
			start_frame: true,
			end_frame: false,
			ref_images: false,
			audio_input: false,
			audio_generate: false,
			ref_video: false,
		},
		costEstimate: 0.302,
		processingTime: 60,
	});
}

export function registerImageToImageModels(): void {
	ModelRegistry.register({
		key: "photon",
		name: "Luma Photon Flash",
		provider: "Luma AI",
		endpoint: "fal-ai/luma-photon/flash/modify",
		categories: ["image_to_image"],
		description:
			"Creative, personalizable, and intelligent image modification model",
		pricing: { per_megapixel: 0.019 },
		aspectRatios: ["1:1", "16:9", "9:16", "4:3", "3:4", "21:9", "9:21"],
		defaults: { strength: 0.8, aspect_ratio: "1:1" },
		features: [
			"Fast processing",
			"High-quality results",
			"Creative modifications",
			"Personalizable outputs",
			"Aspect ratio control",
		],
		costEstimate: 0.02,
		processingTime: 8,
	});

	ModelRegistry.register({
		key: "photon_base",
		name: "Luma Photon Base",
		provider: "Luma AI",
		endpoint: "fal-ai/luma-photon/modify",
		categories: ["image_to_image"],
		description:
			"Most creative, personalizable, and intelligent visual model for creatives",
		pricing: { per_megapixel: 0.019 },
		aspectRatios: ["1:1", "16:9", "9:16", "4:3", "3:4", "21:9", "9:21"],
		defaults: { strength: 0.8, aspect_ratio: "1:1" },
		features: [
			"Step-function change in cost",
			"High-quality image generation",
			"Creative image editing",
			"Prompt-based modifications",
			"Commercial use ready",
		],
		costEstimate: 0.03,
		processingTime: 12,
	});

	ModelRegistry.register({
		key: "kontext",
		name: "FLUX Kontext Dev",
		provider: "Black Forest Labs",
		endpoint: "fal-ai/flux-kontext/dev",
		categories: ["image_to_image"],
		description:
			"Frontier image editing model focused on contextual understanding",
		pricing: { per_image: 0.025 },
		aspectRatios: ["auto"],
		defaults: {
			num_inference_steps: 28,
			guidance_scale: 2.5,
			resolution_mode: "auto",
		},
		features: [
			"Contextual understanding",
			"Nuanced modifications",
			"Style preservation",
			"Iterative editing",
			"Precise control",
		],
		costEstimate: 0.025,
		processingTime: 15,
	});

	ModelRegistry.register({
		key: "kontext_multi",
		name: "FLUX Kontext [max] Multi",
		provider: "Black Forest Labs",
		endpoint: "fal-ai/flux-pro/kontext/max/multi",
		categories: ["image_to_image"],
		description:
			"Experimental multi-image version of FLUX Kontext [max] with advanced capabilities",
		pricing: { per_image: 0.04 },
		aspectRatios: [
			"21:9",
			"16:9",
			"4:3",
			"3:2",
			"1:1",
			"2:3",
			"3:4",
			"9:16",
			"9:21",
		],
		defaults: {},
		features: [
			"Multi-image input support",
			"Advanced contextual understanding",
			"Experimental capabilities",
			"High-quality results",
			"Safety tolerance control",
			"Multiple output formats",
		],
		costEstimate: 0.04,
		processingTime: 25,
	});

	ModelRegistry.register({
		key: "seededit",
		name: "ByteDance SeedEdit v3",
		provider: "ByteDance",
		endpoint: "fal-ai/bytedance/seededit/v3/edit-image",
		categories: ["image_to_image"],
		description:
			"Accurate image editing model with excellent content preservation",
		pricing: { per_image: 0.02 },
		defaults: { guidance_scale: 0.5 },
		features: [
			"Accurate editing instruction following",
			"Effective content preservation",
			"Commercial use ready",
			"Simple parameter set",
			"High-quality results",
			"ByteDance developed",
		],
		costEstimate: 0.02,
		processingTime: 10,
	});

	ModelRegistry.register({
		key: "clarity",
		name: "Clarity Upscaler",
		provider: "FAL AI",
		endpoint: "fal-ai/clarity-upscaler",
		categories: ["image_to_image"],
		description:
			"High-quality image upscaling with optional creative enhancement",
		pricing: { per_image: 0.05 },
		defaults: { scale: 2, enable_enhancement: true },
		features: [
			"Up to 4x upscaling",
			"Optional creative enhancement",
			"Maintains image quality",
			"Fast processing",
			"Commercial use ready",
			"Prompt-based enhancement",
		],
		costEstimate: 0.05,
		processingTime: 30,
	});

	ModelRegistry.register({
		key: "nano_banana_pro_edit",
		name: "Nano Banana Pro Edit",
		provider: "FAL AI",
		endpoint: "fal-ai/nano-banana-pro/edit",
		categories: ["image_to_image"],
		description:
			"Multi-image editing and composition model with resolution control",
		pricing: { "1K_2K": 0.015, "4K": 0.03 },
		aspectRatios: [
			"auto",
			"21:9",
			"16:9",
			"3:2",
			"4:3",
			"5:4",
			"1:1",
			"4:5",
			"3:4",
			"2:3",
			"9:16",
		],
		resolutions: ["1K", "2K", "4K"],
		defaults: {
			aspect_ratio: "auto",
			resolution: "1K",
			output_format: "png",
			num_images: 1,
			sync_mode: true,
		},
		features: [
			"Multi-image input (up to 4)",
			"11 aspect ratio options",
			"Up to 4K resolution",
			"Optional web search enhancement",
			"Fast processing",
			"Commercial use ready",
		],
		costEstimate: 0.015,
		processingTime: 8,
	});

	ModelRegistry.register({
		key: "gpt_image_1_5_edit",
		name: "GPT Image 1.5 Edit",
		provider: "OpenAI (via FAL)",
		endpoint: "fal-ai/gpt-image-1.5/edit",
		categories: ["image_to_image"],
		description:
			"GPT-powered image editing with natural language understanding",
		pricing: { per_image: 0.02 },
		defaults: { strength: 0.75 },
		features: [
			"GPT-powered editing",
			"Natural language understanding",
			"High-quality results",
			"Creative modifications",
			"Commercial use ready",
		],
		costEstimate: 0.02,
		processingTime: 10,
	});
}
