// Generated by scripts/import-gl-transitions.ts from https://github.com/gl-transitions/gl-transitions
// at commit 902218a1b63773ac0d0d9f491951da3392365bfe. Do not edit; rerun the script instead.
import type { TransitionLabRecipe } from "./transition-lab-catalog.js";

export const GL_TRANSITION_RECIPES_13: TransitionLabRecipe[] = [
	{
		id: "gl-mosaic-transition",
		name: "Mosaic Transition",
		localizedName: "Mosaic Transition",
		description: "gl-transitions/mosaic_transition.glsl by YueDev (MIT)",
		defaultDuration: 0.8,
		clip: { type: "shader", easing: "linear" },
		shader: {
			fragmentSource: `
precision highp float;
uniform sampler2D uFrom;
uniform sampler2D uTo;
uniform float uProgress;
uniform float uIntensity;
uniform vec2 uResolution;
varying vec2 vUv;

uniform float uRatio;
#define progress uProgress
#define ratio uRatio
vec4 getFromColor(vec2 uv) { return texture2D(uFrom, uv); }
vec4 getToColor(vec2 uv) { return texture2D(uTo, uv); }

// Author: YueDev
// License: MIT

const float mosaicNum = 10.0;

vec2 getMosaicUV(vec2 uv) {
  float mosaicWidth = 2.0 / mosaicNum * min(progress, 1.0 - progress);
  float mX = floor(uv.x / mosaicWidth) + 0.5;
  float mY = floor(uv.y / mosaicWidth) + 0.5;
  return vec2(mX * mosaicWidth, mY * mosaicWidth);
}

vec4 transition (vec2 uv) {
  vec2 mosaicUV = min(progress, 1.0 - progress) == 0.0 ? uv : getMosaicUV(uv);
  return mix(getFromColor(mosaicUV), getToColor(mosaicUV), progress * progress);
}


void main() {
	gl_FragColor = transition(vUv);
}
`,
			origin: "gl-transitions",
			license: "MIT",
			binaryAssets: false,
			author: "YueDev",
			sourceFile: "mosaic_transition.glsl",
		},
	},
	{
		id: "gl-multiply-blend",
		name: "Multiply Blend",
		localizedName: "Multiply Blend",
		description: "gl-transitions/multiply_blend.glsl by Fernando Kuteken (MIT)",
		defaultDuration: 0.8,
		clip: { type: "shader", easing: "linear" },
		shader: {
			fragmentSource: `
precision highp float;
uniform sampler2D uFrom;
uniform sampler2D uTo;
uniform float uProgress;
uniform float uIntensity;
uniform vec2 uResolution;
varying vec2 vUv;

uniform float uRatio;
#define progress uProgress
#define ratio uRatio
vec4 getFromColor(vec2 uv) { return texture2D(uFrom, uv); }
vec4 getToColor(vec2 uv) { return texture2D(uTo, uv); }

// Author: Fernando Kuteken
// License: MIT

vec4 blend(vec4 a, vec4 b) {
  return a * b;
}

vec4 transition (vec2 uv) {
  
  vec4 blended = blend(getFromColor(uv), getToColor(uv));
  
  if (progress < 0.5)
    return mix(getFromColor(uv), blended, 2.0 * progress);
  else
    return mix(blended, getToColor(uv), 2.0 * progress - 1.0);
}



void main() {
	gl_FragColor = transition(vUv);
}
`,
			origin: "gl-transitions",
			license: "MIT",
			binaryAssets: false,
			author: "Fernando Kuteken",
			sourceFile: "multiply_blend.glsl",
		},
	},
	{
		id: "gl-old-tv-lost-signal",
		name: "Old Tv Lost Signal",
		localizedName: "Old Tv Lost Signal",
		description:
			"gl-transitions/old_tv_lost_signal.glsl by mernking gitlab: Godswork (MIT)",
		defaultDuration: 0.8,
		clip: { type: "shader", easing: "linear" },
		shader: {
			fragmentSource: `
precision highp float;
uniform sampler2D uFrom;
uniform sampler2D uTo;
uniform float uProgress;
uniform float uIntensity;
uniform vec2 uResolution;
varying vec2 vUv;

uniform float uRatio;
#define progress uProgress
#define ratio uRatio
vec4 getFromColor(vec2 uv) { return texture2D(uFrom, uv); }
vec4 getToColor(vec2 uv) { return texture2D(uTo, uv); }

// Author: mernking gitlab: Godswork
// License: MIT

float hash(vec2 p) {
    return fract(sin(dot(p, vec2(127.1, 311.7))) * 43758.5453);
}

vec4 transition(vec2 uv) {

    float p = progress;
    float strength = sin(p * 3.14159265);

    vec2 tv = uv;

    vec4 fromColor = getFromColor(tv);
    vec4 toColor   = getToColor(tv);

    vec4 color = mix(fromColor, toColor, p);

    // horizontal tracking lines (key effect)
    float lineY = floor(tv.y * 120.0);

    float noise = hash(vec2(lineY, p * 20.0));

    float line = step(0.92, noise);

    // make lines drift during transition
    float drift =
        sin(tv.y * 30.0 + p * 10.0)
        * 0.02
        * strength;

    vec4 shiftedFrom = getFromColor(tv + vec2(drift, 0.0));
    vec4 shiftedTo   = getToColor(tv + vec2(drift, 0.0));

    vec4 lineColor = mix(shiftedFrom, shiftedTo, p);

    // apply tearing only on selected scanlines
    color = mix(color, lineColor, line * strength);

    // mild scanline darkening (CRT feel)
    float scan =
        sin(tv.y * 900.0) * 0.03;

    color.rgb -= scan * strength;

    return color;
}


void main() {
	gl_FragColor = transition(vUv);
}
`,
			origin: "gl-transitions",
			license: "MIT",
			binaryAssets: false,
			author: "mernking gitlab: Godswork",
			sourceFile: "old_tv_lost_signal.glsl",
		},
	},
	{
		id: "gl-parametric-glitch",
		name: "Parametric Glitch",
		localizedName: "Parametric Glitch",
		description:
			"gl-transitions/parametric_glitch.glsl by Yoni Maltsman @friendlyspinach (MIT)",
		defaultDuration: 0.8,
		clip: { type: "shader", easing: "linear" },
		shader: {
			fragmentSource: `
precision highp float;
uniform sampler2D uFrom;
uniform sampler2D uTo;
uniform float uProgress;
uniform float uIntensity;
uniform vec2 uResolution;
varying vec2 vUv;

uniform float uRatio;
#define progress uProgress
#define ratio uRatio
vec4 getFromColor(vec2 uv) { return texture2D(uFrom, uv); }
vec4 getToColor(vec2 uv) { return texture2D(uTo, uv); }

// Author: Yoni Maltsman @friendlyspinach
// License: MIT



const float ampx = 1.0;
const float ampy = 1.0;

vec4 transition (vec2 uv) {
  vec4 from = getFromColor(uv);
  vec4 to = getToColor(uv);
  float r = from.r;
  float g = from.g;
  float b = from.b;
  float sphere = r*r + g*g + b*b - 1.0; //3 to 1
  float spiralX = cos(sphere - uv.x/(progress + .01));
  float spiralY = sin(sphere - uv.y/(progress+.01));
  vec2 st = uv;
  st.x = fract(ampx*st.x*spiralX); //1 to 2
  st.y = fract(ampy*st.y*spiralY);
  vec2 diff = uv - st;
  from = getFromColor(uv + progress*diff);
  return mix(from, to, progress);
}


void main() {
	gl_FragColor = transition(vUv);
}
`,
			origin: "gl-transitions",
			license: "MIT",
			binaryAssets: false,
			author: "Yoni Maltsman @friendlyspinach",
			sourceFile: "parametric_glitch.glsl",
		},
	},
	{
		id: "gl-perlin",
		name: "Perlin",
		localizedName: "Perlin",
		description: "gl-transitions/perlin.glsl by Rich Harris (MIT)",
		defaultDuration: 0.8,
		clip: { type: "shader", easing: "linear" },
		shader: {
			fragmentSource: `
precision highp float;
uniform sampler2D uFrom;
uniform sampler2D uTo;
uniform float uProgress;
uniform float uIntensity;
uniform vec2 uResolution;
varying vec2 vUv;

uniform float uRatio;
#define progress uProgress
#define ratio uRatio
vec4 getFromColor(vec2 uv) { return texture2D(uFrom, uv); }
vec4 getToColor(vec2 uv) { return texture2D(uTo, uv); }

// Author: Rich Harris
// License: MIT

#ifdef GL_ES
#endif

const float scale = 4.0;
const float smoothness = 0.01;

const float seed = 12.9898;

// http://byteblacksmith.com/improvements-to-the-canonical-one-liner-glsl-rand-for-opengl-es-2-0/
float random(vec2 co)
{
    float a = seed;
    float b = 78.233;
    float c = 43758.5453;
    float dt= dot(co.xy ,vec2(a,b));
    float sn= mod(dt,3.14);
    return fract(sin(sn) * c);
}

// 2D Noise based on Morgan McGuire @morgan3d
// https://www.shadertoy.com/view/4dS3Wd
float noise (in vec2 st) {
    vec2 i = floor(st);
    vec2 f = fract(st);

    // Four corners in 2D of a tile
    float a = random(i);
    float b = random(i + vec2(1.0, 0.0));
    float c = random(i + vec2(0.0, 1.0));
    float d = random(i + vec2(1.0, 1.0));

    // Smooth Interpolation

    // Cubic Hermine Curve.  Same as SmoothStep()
    vec2 u = f*f*(3.0-2.0*f);
    // u = smoothstep(0.,1.,f);

    // Mix 4 coorners porcentages
    return mix(a, b, u.x) +
            (c - a)* u.y * (1.0 - u.x) +
            (d - b) * u.x * u.y;
}

vec4 transition (vec2 uv) {
  vec4 from = getFromColor(uv);
  vec4 to = getToColor(uv);
  float n = noise(uv * scale);

  float p = mix(-smoothness, 1.0 + smoothness, progress);
  float lower = p - smoothness;
  float higher = p + smoothness;

  float q = smoothstep(lower, higher, n);

  return mix(
    from,
    to,
    1.0 - q
  );
}


void main() {
	gl_FragColor = transition(vUv);
}
`,
			origin: "gl-transitions",
			license: "MIT",
			binaryAssets: false,
			author: "Rich Harris",
			sourceFile: "perlin.glsl",
		},
	},
	{
		id: "gl-pinwheel",
		name: "Pinwheel",
		localizedName: "Pinwheel",
		description: "gl-transitions/pinwheel.glsl by Mr Speaker (MIT)",
		defaultDuration: 0.8,
		clip: { type: "shader", easing: "linear" },
		shader: {
			fragmentSource: `
precision highp float;
uniform sampler2D uFrom;
uniform sampler2D uTo;
uniform float uProgress;
uniform float uIntensity;
uniform vec2 uResolution;
varying vec2 vUv;

uniform float uRatio;
#define progress uProgress
#define ratio uRatio
vec4 getFromColor(vec2 uv) { return texture2D(uFrom, uv); }
vec4 getToColor(vec2 uv) { return texture2D(uTo, uv); }

// Author: Mr Speaker
// License: MIT

const float speed = 2.0;

vec4 transition(vec2 uv) {
  
  vec2 p = uv.xy / vec2(1.0).xy;
  
  float circPos = atan(p.y - 0.5, p.x - 0.5) + progress * speed;
  float modPos = mod(circPos, 3.1415 / 4.);
  float signed = sign(progress - modPos);
  
  return mix(getToColor(p), getFromColor(p), step(signed, 0.5));
  
}


void main() {
	gl_FragColor = transition(vUv);
}
`,
			origin: "gl-transitions",
			license: "MIT",
			binaryAssets: false,
			author: "Mr Speaker",
			sourceFile: "pinwheel.glsl",
		},
	},
	{
		id: "gl-pixelize",
		name: "Pixelize",
		localizedName: "Pixelize",
		description: "gl-transitions/pixelize.glsl by gre (MIT)",
		defaultDuration: 0.8,
		clip: { type: "shader", easing: "linear" },
		shader: {
			fragmentSource: `
precision highp float;
uniform sampler2D uFrom;
uniform sampler2D uTo;
uniform float uProgress;
uniform float uIntensity;
uniform vec2 uResolution;
varying vec2 vUv;

uniform float uRatio;
#define progress uProgress
#define ratio uRatio
vec4 getFromColor(vec2 uv) { return texture2D(uFrom, uv); }
vec4 getToColor(vec2 uv) { return texture2D(uTo, uv); }

// Author: gre
// License: MIT
// forked from https://gist.github.com/benraziel/c528607361d90a072e98

// minimum number of squares (when the effect is at its higher level)
const ivec2 squaresMin = ivec2(20);
// zero disable the stepping
const int steps = 50;

float d = min(progress, 1.0 - progress);
float dist = steps>0 ? ceil(d * float(steps)) / float(steps) : d;
vec2 squareSize = 2.0 * dist / vec2(squaresMin);

vec4 transition(vec2 uv) {
  vec2 p = dist>0.0 ? (floor(uv / squareSize) + 0.5) * squareSize : uv;
  return mix(getFromColor(p), getToColor(p), progress);
}


void main() {
	gl_FragColor = transition(vUv);
}
`,
			origin: "gl-transitions",
			license: "MIT",
			binaryAssets: false,
			author: "gre",
			sourceFile: "pixelize.glsl",
		},
	},
	{
		id: "gl-polar-function",
		name: "Polar Function",
		localizedName: "Polar Function",
		description: "gl-transitions/polar_function.glsl by Fernando Kuteken (MIT)",
		defaultDuration: 0.8,
		clip: { type: "shader", easing: "linear" },
		shader: {
			fragmentSource: `
precision highp float;
uniform sampler2D uFrom;
uniform sampler2D uTo;
uniform float uProgress;
uniform float uIntensity;
uniform vec2 uResolution;
varying vec2 vUv;

uniform float uRatio;
#define progress uProgress
#define ratio uRatio
vec4 getFromColor(vec2 uv) { return texture2D(uFrom, uv); }
vec4 getToColor(vec2 uv) { return texture2D(uTo, uv); }

// Author: Fernando Kuteken
// License: MIT

#define PI 3.14159265359

const int segments = 5;

vec4 transition (vec2 uv) {
  
  float angle = atan(uv.y - 0.5, uv.x - 0.5) - 0.5 * PI;
  float normalized = (angle + 1.5 * PI) * (2.0 * PI);
  
  float radius = (cos(float(segments) * angle) + 4.0) / 4.0;
  float difference = length(uv - vec2(0.5, 0.5));
  
  if (difference > radius * progress)
    return getFromColor(uv);
  else
    return getToColor(uv);
}


void main() {
	gl_FragColor = transition(vUv);
}
`,
			origin: "gl-transitions",
			license: "MIT",
			binaryAssets: false,
			author: "Fernando Kuteken",
			sourceFile: "polar_function.glsl",
		},
	},
	{
		id: "gl-power-kaleido",
		name: "Power Kaleido",
		localizedName: "Power Kaleido",
		description: "gl-transitions/powerKaleido.glsl by Boundless (MIT)",
		defaultDuration: 0.8,
		clip: { type: "shader", easing: "linear" },
		shader: {
			fragmentSource: `
precision highp float;
uniform sampler2D uFrom;
uniform sampler2D uTo;
uniform float uProgress;
uniform float uIntensity;
uniform vec2 uResolution;
varying vec2 vUv;

uniform float uRatio;
#define progress uProgress
#define ratio uRatio
vec4 getFromColor(vec2 uv) { return texture2D(uFrom, uv); }
vec4 getToColor(vec2 uv) { return texture2D(uTo, uv); }

// Name: Power Kaleido
// Author: Boundless
// License: MIT
#define PI 3.14159265358979
const float rad = 120.; // change this value to get different mirror effects
const float deg = rad / 180. * PI;
const float scale = 2.0;
const float z = 1.5;
float dist = scale / 10.;
const float speed = 5.;
vec2 refl(vec2 p,vec2 o,vec2 n)
{
	return 2.0*o+2.0*n*dot(p-o,n)-p;
}

vec2 rot(vec2 p, vec2 o, float a)
{
    float s = sin(a);
    float c = cos(a);
	return o + mat2(c, -s, s, c) * (p - o);
}

vec4 mainImage(vec2 uv)
{
  vec2 uv0 = uv;
	uv -= 0.5;
  uv.x *= ratio;
  uv *= z;
  uv = rot(uv, vec2(0.0), progress*speed);
  // uv.x = fract(uv.x/l/3.0)*l*3.0;
	float theta = progress*6.+PI/.5;
	for(int iter = 0; iter < 10; iter++) {
    for(float i = 0.; i < 2. * PI; i+=deg) {
	    float ts = sign(asin(cos(i))) == 1.0 ? 1.0 : 0.0;
      if(((ts == 1.0) && (uv.y-dist*cos(i) > tan(i)*(uv.x+dist*+sin(i)))) || ((ts == 0.0) && (uv.y-dist*cos(i) < tan(i)*(uv.x+dist*+sin(i))))) {
        uv = refl(vec2(uv.x+sin(i)*dist*2.,uv.y-cos(i)*dist*2.), vec2(0.,0.), vec2(cos(i),sin(i)));
      }
    }
  }
  uv += 0.5;
  uv = rot(uv, vec2(0.5), progress*-speed);
  uv -= 0.5;
  uv.x /= ratio;
  uv += 0.5;
  uv = 2.*abs(uv/2.-floor(uv/2.+0.5));
  vec2 uvMix = mix(uv,uv0,cos(progress*PI*2.)/2.+0.5);
  vec4 color = mix(getFromColor(uvMix),getToColor(uvMix),cos((progress-1.)*PI)/2.+0.5);
	return color;
    
}
vec4 transition (vec2 uv) {
  vec4 color = mainImage(uv);
  return color;
}


void main() {
	gl_FragColor = transition(vUv);
}
`,
			origin: "gl-transitions",
			license: "MIT",
			binaryAssets: false,
			author: "Boundless",
			sourceFile: "powerKaleido.glsl",
		},
	},
];
