// Generated by scripts/import-gl-transitions.ts from https://github.com/gl-transitions/gl-transitions
// at commit 902218a1b63773ac0d0d9f491951da3392365bfe. Do not edit; rerun the script instead.
import type { TransitionLabRecipe } from "./transition-lab-catalog.js";

export const GL_TRANSITION_RECIPES_07: TransitionLabRecipe[] = [
	{
		id: "gl-rotate-scale-vanish",
		name: "Rotate Scale Vanish",
		localizedName: "Rotate Scale Vanish",
		description: "gl-transitions/RotateScaleVanish.glsl by Mark Craig (MIT)",
		defaultDuration: 0.8,
		clip: { type: "shader", easing: "linear" },
		shader: {
			fragmentSource: `
precision highp float;
uniform sampler2D uFrom;
uniform sampler2D uTo;
uniform float uProgress;
uniform float uIntensity;
uniform vec2 uResolution;
varying vec2 vUv;

uniform float uRatio;
#define progress uProgress
#define ratio uRatio
vec4 getFromColor(vec2 uv) { return texture2D(uFrom, uv); }
vec4 getToColor(vec2 uv) { return texture2D(uTo, uv); }

// Author: Mark Craig
// mrmcsoftware on github and youtube ( http://www.youtube.com/MrMcSoftware )
// License: MIT

// RotateScaleVanish Transition by Mark Craig (Copyright © 2022)

const bool FadeInSecond = true;
const bool ReverseEffect = false;
const bool ReverseRotation = false;

#define M_PI 3.14159265358979323846
#define _TWOPI 6.283185307179586476925286766559

vec4 transition(vec2 uv)
{
vec2 iResolution = vec2(ratio, 1.0);
float t = ReverseEffect ? 1.0 - progress : progress;
float theta = ReverseRotation ? _TWOPI * t : -_TWOPI * t;
float c1 = cos(theta);
float s1 = sin(theta);
float rad = max(0.00001, 1.0 - t);
float xc1 = (uv.x - 0.5) * iResolution.x;
float yc1 = (uv.y - 0.5) * iResolution.y;
float xc2 = (xc1 * c1 - yc1 * s1) / rad;
float yc2 = (xc1 * s1 + yc1 * c1) / rad;
vec2 uv2 = vec2(xc2 + iResolution.x / 2.0, yc2 + iResolution.y / 2.0);
vec4 col3;
vec4 ColorTo = ReverseEffect ? getFromColor(uv) : getToColor(uv);
if ((uv2.x >= 0.0) && (uv2.x <= iResolution.x) && (uv2.y >= 0.0) && (uv2.y <= iResolution.y))
	{
	uv2 /= iResolution;
	col3 = ReverseEffect ? getToColor(uv2) : getFromColor(uv2);
	}
else { col3 = FadeInSecond ? vec4(0.0, 0.0, 0.0, 1.0) : ColorTo; }
return((1.0 - t) * col3 + t * ColorTo); // could have used mix
}


void main() {
	gl_FragColor = transition(vUv);
}
`,
			origin: "gl-transitions",
			license: "MIT",
			binaryAssets: false,
			author: "Mark Craig",
			sourceFile: "RotateScaleVanish.glsl",
		},
	},
	{
		id: "gl-simple-flip",
		name: "Simple Flip",
		localizedName: "Simple Flip",
		description: "gl-transitions/SimpleFlip.glsl by nwoeanhinnogaehr (MIT)",
		defaultDuration: 0.8,
		clip: { type: "shader", easing: "linear" },
		shader: {
			fragmentSource: `
precision highp float;
uniform sampler2D uFrom;
uniform sampler2D uTo;
uniform float uProgress;
uniform float uIntensity;
uniform vec2 uResolution;
varying vec2 vUv;

uniform float uRatio;
#define progress uProgress
#define ratio uRatio
vec4 getFromColor(vec2 uv) { return texture2D(uFrom, uv); }
vec4 getToColor(vec2 uv) { return texture2D(uTo, uv); }

// Author: nwoeanhinnogaehr
// License: MIT
// Ported from https://gist.github.com/nwoeanhinnogaehr/408045772d255df97520

vec4 transition(vec2 uv) {
  vec2 q = uv;
  uv.x = (uv.x - 0.5) / abs(progress - 0.5) * 0.5 + 0.5;
  vec4 a = getFromColor(uv);
  vec4 b = getToColor(uv);
  return vec4(mix(a, b, step(0.5, progress)).rgb * step(abs(q.x - 0.5), abs(progress - 0.5)), 1.0);
}


void main() {
	gl_FragColor = transition(vUv);
}
`,
			origin: "gl-transitions",
			license: "MIT",
			binaryAssets: false,
			author: "nwoeanhinnogaehr",
			sourceFile: "SimpleFlip.glsl",
		},
	},
	{
		id: "gl-simple-zoom",
		name: "Simple Zoom",
		localizedName: "Simple Zoom",
		description: "gl-transitions/SimpleZoom.glsl by 0gust1 (MIT)",
		defaultDuration: 0.8,
		clip: { type: "shader", easing: "linear" },
		shader: {
			fragmentSource: `
precision highp float;
uniform sampler2D uFrom;
uniform sampler2D uTo;
uniform float uProgress;
uniform float uIntensity;
uniform vec2 uResolution;
varying vec2 vUv;

uniform float uRatio;
#define progress uProgress
#define ratio uRatio
vec4 getFromColor(vec2 uv) { return texture2D(uFrom, uv); }
vec4 getToColor(vec2 uv) { return texture2D(uTo, uv); }

// Author: 0gust1
// License: MIT

const float zoom_quickness = 0.8;
float nQuick = clamp(zoom_quickness,0.2,1.0);

vec2 zoom(vec2 uv, float amount) {
  return 0.5 + ((uv - 0.5) * (1.0-amount));	
}

vec4 transition (vec2 uv) {
  return mix(
    getFromColor(zoom(uv, smoothstep(0.0, nQuick, progress))),
    getToColor(uv),
   smoothstep(nQuick-0.2, 1.0, progress)
  );
}

void main() {
	gl_FragColor = transition(vUv);
}
`,
			origin: "gl-transitions",
			license: "MIT",
			binaryAssets: false,
			author: "0gust1",
			sourceFile: "SimpleZoom.glsl",
		},
	},
	{
		id: "gl-simple-zoom-out",
		name: "Simple Zoom Out",
		localizedName: "Simple Zoom Out",
		description: "gl-transitions/SimpleZoomOut.glsl by Tianshuo (MIT)",
		defaultDuration: 0.8,
		clip: { type: "shader", easing: "linear" },
		shader: {
			fragmentSource: `
precision highp float;
uniform sampler2D uFrom;
uniform sampler2D uTo;
uniform float uProgress;
uniform float uIntensity;
uniform vec2 uResolution;
varying vec2 vUv;

uniform float uRatio;
#define progress uProgress
#define ratio uRatio
vec4 getFromColor(vec2 uv) { return texture2D(uFrom, uv); }
vec4 getToColor(vec2 uv) { return texture2D(uTo, uv); }

// Author: Tianshuo
// License: MIT


const float zoom_quickness = 0.8;
const bool fade = true;
float nQuick = clamp(zoom_quickness,0.2,1.0);

vec2 zoom(vec2 uv, float amount) {
  return 0.5 + ((uv - 0.5) * (1.0-amount));	
}

vec4 transition (vec2 uv) {
  return mix(
    getFromColor(uv),
    getToColor(zoom(uv,1.-smoothstep(1.-nQuick, 1., progress))),
   fade?smoothstep(1.0-nQuick, 1., progress):(progress<1.0-nQuick?0.0:1.0)
  );
}


void main() {
	gl_FragColor = transition(vUv);
}
`,
			origin: "gl-transitions",
			license: "MIT",
			binaryAssets: false,
			author: "Tianshuo",
			sourceFile: "SimpleZoomOut.glsl",
		},
	},
	{
		id: "gl-slides",
		name: "Slides",
		localizedName: "Slides",
		description: "gl-transitions/Slides.glsl by Mark Craig (MIT)",
		defaultDuration: 0.8,
		clip: { type: "shader", easing: "linear" },
		shader: {
			fragmentSource: `
precision highp float;
uniform sampler2D uFrom;
uniform sampler2D uTo;
uniform float uProgress;
uniform float uIntensity;
uniform vec2 uResolution;
varying vec2 vUv;

uniform float uRatio;
#define progress uProgress
#define ratio uRatio
vec4 getFromColor(vec2 uv) { return texture2D(uFrom, uv); }
vec4 getToColor(vec2 uv) { return texture2D(uTo, uv); }

// Author: Mark Craig
// mrmcsoftware on github and youtube ( http://www.youtube.com/MrMcSoftware )
// License: MIT

// Slides Transition by Mark Craig (Copyright © 2022)

const int type = 0;
const bool In = false;
// type: slide to/from which edge, which corner, or center
// In: if true slide new image in, otherwise slide old image out

#define rad2 rad / 2.0

vec4 transition(vec2 uv)
{
vec2 uv0 = uv;
float rad = In ? progress : 1.0 - progress;
float xc1, yc1;
// I used if/else instead of switch in case it's an old GPU
if (type == 0) { xc1 = .5 - rad2; yc1 = 0.0; }
else if (type == 1) { xc1 = 1.0 - rad; yc1 = .5 - rad2; }
else if (type == 2) { xc1 = .5 - rad2; yc1 = 1.0 - rad; }
else if (type == 3) { xc1 = 0.0; yc1 = .5 - rad2; }
else if (type == 4) { xc1 = 1.0 - rad; yc1 = 0.0; }
else if (type == 5) { xc1 = 1.0 - rad; yc1 = 1.0 - rad; }
else if (type == 6) { xc1 = 0.0; yc1 = 1.0 - rad; }
else if (type == 7) { xc1 = 0.0; yc1 = 0.0; }
else if (type == 8) { xc1 = .5 - rad2; yc1 = .5 - rad2; }
uv.y = 1.0 - uv.y;
vec2 uv2;
if ((uv.x >= xc1) && (uv.x <= xc1 + rad) && (uv.y >= yc1) && (uv.y <= yc1 + rad))
	{
	uv2 = vec2((uv.x - xc1) / rad, 1.0 - (uv.y - yc1) / rad);
	return(In ? getToColor(uv2) : getFromColor(uv2));
	}
return(In ? getFromColor(uv0) : getToColor(uv0));
}


void main() {
	gl_FragColor = transition(vUv);
}
`,
			origin: "gl-transitions",
			license: "MIT",
			binaryAssets: false,
			author: "Mark Craig",
			sourceFile: "Slides.glsl",
		},
	},
	{
		id: "gl-star-wipe",
		name: "Star Wipe",
		localizedName: "Star Wipe",
		description: "gl-transitions/StarWipe.glsl by Ben Lucas (MIT)",
		defaultDuration: 0.8,
		clip: { type: "shader", easing: "linear" },
		shader: {
			fragmentSource: `
precision highp float;
uniform sampler2D uFrom;
uniform sampler2D uTo;
uniform float uProgress;
uniform float uIntensity;
uniform vec2 uResolution;
varying vec2 vUv;

uniform float uRatio;
#define progress uProgress
#define ratio uRatio
vec4 getFromColor(vec2 uv) { return texture2D(uFrom, uv); }
vec4 getToColor(vec2 uv) { return texture2D(uTo, uv); }

// Author: Ben Lucas
// License: MIT
#define PI 3.141592653589793
#define STAR_ANGLE 1.2566370614359172

const float border_thickness = 0.01;
const float star_rotation = 0.75;
const vec4 border_color = vec4(1.0);
const vec2 star_center = vec2(0.5);

vec2 rotate(vec2 v, float theta) {
    float cosTheta = cos(theta);
    float sinTheta = sin(theta);

    return vec2(
        cosTheta * v.x - sinTheta * v.y,
        sinTheta * v.x + cosTheta * v.y
    );
}

bool inStar(vec2 uv, vec2 center, float radius){
  vec2 uv_centered = uv - center;
  uv_centered = rotate(uv_centered, star_rotation * STAR_ANGLE);
  float theta = atan(uv_centered.y, uv_centered.x) + PI;

  vec2 uv_rotated = rotate(uv_centered, -STAR_ANGLE * (floor(theta / STAR_ANGLE) + 0.5));

  float slope = 0.3;
  if(uv_rotated.y > 0.0){
      return (radius + uv_rotated.x * slope > uv_rotated.y);
  } else {
     return (-radius - uv_rotated.x * slope < uv_rotated.y);
  }
}

vec4 transition (vec2 uv) {
  float progressScaled = (2.0 * border_thickness + 1.0) * progress - border_thickness;
  if(inStar(uv, star_center, progressScaled)){
    return getToColor(uv);
  } else if(inStar(uv, star_center, progressScaled+border_thickness)){
    return border_color;
  } else {
    return getFromColor(uv);
  }
}


void main() {
	gl_FragColor = transition(vUv);
}
`,
			origin: "gl-transitions",
			license: "MIT",
			binaryAssets: false,
			author: "Ben Lucas",
			sourceFile: "StarWipe.glsl",
		},
	},
	{
		id: "gl-static-fade",
		name: "Static Fade",
		localizedName: "Static Fade",
		description: "gl-transitions/StaticFade.glsl by Ben Lucas (MIT)",
		defaultDuration: 0.8,
		clip: { type: "shader", easing: "linear" },
		shader: {
			fragmentSource: `
precision highp float;
uniform sampler2D uFrom;
uniform sampler2D uTo;
uniform float uProgress;
uniform float uIntensity;
uniform vec2 uResolution;
varying vec2 vUv;

uniform float uRatio;
#define progress uProgress
#define ratio uRatio
vec4 getFromColor(vec2 uv) { return texture2D(uFrom, uv); }
vec4 getToColor(vec2 uv) { return texture2D(uTo, uv); }

// Author: Ben Lucas
// License: MIT

const float n_noise_pixels = 200.0;
const float static_luminosity = 0.8;

float rnd (vec2 st) {
    return fract(sin(dot(st.xy,
                         vec2(10.5302340293,70.23492931)))*
        12345.5453123);
}

vec4 staticNoise (vec2 st, float offset, float luminosity) {
  float staticR = luminosity * rnd(st * vec2(offset * 2.0, offset * 3.0));
  float staticG = luminosity * rnd(st * vec2(offset * 3.0, offset * 5.0));
  float staticB = luminosity * rnd(st * vec2(offset * 5.0, offset * 7.0));
  return vec4(staticR, staticG, staticB, 1.0);
}

float staticIntensity(float t)
{
  float transitionProgress = abs(2.0*(t-0.5));
  float transformedThreshold =1.2*(1.0 - transitionProgress)-0.1;
  return min(1.0, transformedThreshold);
}
  
vec4 transition (vec2 uv) {

  float baseMix = step(0.5, progress);
  vec4 transitionMix = mix(
    getFromColor(uv),
    getToColor(uv),
    baseMix
  );
  
  vec2 uvStatic = floor(uv * n_noise_pixels)/n_noise_pixels;
  
  vec4 staticColor = staticNoise(uvStatic, progress, static_luminosity);

  float staticThresh = staticIntensity(progress);
  float staticMix = step(rnd(uvStatic), staticThresh);

  return mix(transitionMix, staticColor, staticMix);
}


void main() {
	gl_FragColor = transition(vUv);
}
`,
			origin: "gl-transitions",
			license: "MIT",
			binaryAssets: false,
			author: "Ben Lucas",
			sourceFile: "StaticFade.glsl",
		},
	},
];
