// Generated by scripts/import-gl-transitions.ts from https://github.com/gl-transitions/gl-transitions
// at commit 902218a1b63773ac0d0d9f491951da3392365bfe. Do not edit; rerun the script instead.
import type { TransitionLabRecipe } from "./transition-lab-catalog.js";

export const GL_TRANSITION_RECIPES_06: TransitionLabRecipe[] = [
	{
		id: "gl-overexposure",
		name: "Overexposure",
		localizedName: "Overexposure",
		description: "gl-transitions/Overexposure.glsl by Ben Zhang (MIT)",
		defaultDuration: 0.8,
		clip: { type: "shader", easing: "linear" },
		shader: {
			fragmentSource: `
precision highp float;
uniform sampler2D uFrom;
uniform sampler2D uTo;
uniform float uProgress;
uniform float uIntensity;
uniform vec2 uResolution;
varying vec2 vUv;

uniform float uRatio;
#define progress uProgress
#define ratio uRatio
vec4 getFromColor(vec2 uv) { return texture2D(uFrom, uv); }
vec4 getToColor(vec2 uv) { return texture2D(uTo, uv); }

// Author: Ben Zhang
// License: MIT

const float strength = 0.6;
const float PI = 3.141592653589793;

vec4 transition (vec2 uv) {
  vec4 from = getFromColor(uv);
  vec4 to = getToColor(uv);

  // Multipliers
  float from_m = 1.0 - progress + sin(PI * progress) * strength;
  float to_m = progress + sin(PI * progress) * strength;
  
  return vec4(
    from.r * from.a * from_m + to.r * to.a * to_m,
    from.g * from.a * from_m + to.g * to.a * to_m,
    from.b * from.a * from_m + to.b * to.a * to_m,
    mix(from.a, to.a, progress)
  );
}


void main() {
	gl_FragColor = transition(vUv);
}
`,
			origin: "gl-transitions",
			license: "MIT",
			binaryAssets: false,
			author: "Ben Zhang",
			sourceFile: "Overexposure.glsl",
		},
	},
	{
		id: "gl-polka-dots-curtain",
		name: "Polka Dots Curtain",
		localizedName: "Polka Dots Curtain",
		description: "gl-transitions/PolkaDotsCurtain.glsl by bobylito (MIT)",
		defaultDuration: 0.8,
		clip: { type: "shader", easing: "linear" },
		shader: {
			fragmentSource: `
precision highp float;
uniform sampler2D uFrom;
uniform sampler2D uTo;
uniform float uProgress;
uniform float uIntensity;
uniform vec2 uResolution;
varying vec2 vUv;

uniform float uRatio;
#define progress uProgress
#define ratio uRatio
vec4 getFromColor(vec2 uv) { return texture2D(uFrom, uv); }
vec4 getToColor(vec2 uv) { return texture2D(uTo, uv); }

// Author: bobylito
// License: MIT
const float SQRT_2 = 1.414213562373;
const float dots = 20.0;
const vec2 center = vec2(0, 0);

vec4 transition(vec2 uv) {
  bool nextImage = distance(fract(uv * dots), vec2(0.5, 0.5)) < ( progress / distance(uv, center));
  return nextImage ? getToColor(uv) : getFromColor(uv);
}


void main() {
	gl_FragColor = transition(vUv);
}
`,
			origin: "gl-transitions",
			license: "MIT",
			binaryAssets: false,
			author: "bobylito",
			sourceFile: "PolkaDotsCurtain.glsl",
		},
	},
	{
		id: "gl-puzzle-right",
		name: "Puzzle Right",
		localizedName: "Puzzle Right",
		description: "gl-transitions/PuzzleRight.glsl by JustKirillS (MIT)",
		defaultDuration: 0.8,
		clip: { type: "shader", easing: "linear" },
		shader: {
			fragmentSource: `
precision highp float;
uniform sampler2D uFrom;
uniform sampler2D uTo;
uniform float uProgress;
uniform float uIntensity;
uniform vec2 uResolution;
varying vec2 vUv;

uniform float uRatio;
#define progress uProgress
#define ratio uRatio
vec4 getFromColor(vec2 uv) { return texture2D(uFrom, uv); }
vec4 getToColor(vec2 uv) { return texture2D(uTo, uv); }

// Author: JustKirillS
// License: MIT
// Ported from https://gist.github.com/JustKirillS/714f095318834f4d2375de872c53af1e

const ivec2 size = ivec2(4, 4);
const float pause = 0.1;
const float dividerWidth = 0.005;

float rand(vec2 co) {
  return fract(sin(dot(co, vec2(12.9898, 78.233))) * 43758.5453);
}

float getDelta(vec2 p) {
  vec2 rectangleSize = 1.0 / vec2(size);
  vec2 rectanglePos = floor(vec2(size) * p);
  float top = rectangleSize.y * (rectanglePos.y + 1.0);
  float bottom = rectangleSize.y * rectanglePos.y;
  float left = rectangleSize.x * rectanglePos.x;
  float right = rectangleSize.x * (rectanglePos.x + 1.0);
  float minX = min(abs(p.x - left), abs(p.x - right));
  float minY = min(abs(p.y - top), abs(p.y - bottom));
  return min(minX, minY);
}

vec4 transition(vec2 uv) {
  if (progress < pause) {
    float currentProg = progress / pause;
    float a = 1.0;
    if (getDelta(uv) < dividerWidth) { a = 1.0 - currentProg; }
    return mix(vec4(0.0, 0.0, 0.0, 1.0), getFromColor(uv), a);
  } else if (progress < 1.0 - pause) {
    if (getDelta(uv) < dividerWidth) {
      return vec4(0.0, 0.0, 0.0, 1.0);
    }
    float currentProg = (progress - pause) / (1.0 - pause * 2.0);
    vec2 rectanglePos = floor(vec2(size) * uv);
    float r = rand(rectanglePos) - 0.1;
    float cp = smoothstep(0.0, 1.0 - r, currentProg);
    float rectangleSize = 1.0 / float(size.x);
    float delta = rectanglePos.x * rectangleSize;
    float offset = rectangleSize / 2.0 + delta;
    vec2 p = uv;
    p.x = (p.x - offset) / abs(cp - 0.5) * 0.5 + offset;
    vec4 a = getFromColor(p);
    vec4 b = getToColor(p);
    float s = step(abs(float(size.x) * (uv.x - delta) - 0.5), abs(cp - 0.5));
    return vec4(mix(b, a, step(cp, 0.5)).rgb * s, 1.0);
  } else {
    float currentProg = (progress - 1.0 + pause) / pause;
    float a = 1.0;
    if (getDelta(uv) < dividerWidth) { a = currentProg; }
    return mix(vec4(0.0, 0.0, 0.0, 1.0), getToColor(uv), a);
  }
}


void main() {
	gl_FragColor = transition(vUv);
}
`,
			origin: "gl-transitions",
			license: "MIT",
			binaryAssets: false,
			author: "JustKirillS",
			sourceFile: "PuzzleRight.glsl",
		},
	},
	{
		id: "gl-radial",
		name: "Radial",
		localizedName: "Radial",
		description: "gl-transitions/Radial.glsl by Xaychru (MIT)",
		defaultDuration: 0.8,
		clip: { type: "shader", easing: "linear" },
		shader: {
			fragmentSource: `
precision highp float;
uniform sampler2D uFrom;
uniform sampler2D uTo;
uniform float uProgress;
uniform float uIntensity;
uniform vec2 uResolution;
varying vec2 vUv;

uniform float uRatio;
#define progress uProgress
#define ratio uRatio
vec4 getFromColor(vec2 uv) { return texture2D(uFrom, uv); }
vec4 getToColor(vec2 uv) { return texture2D(uTo, uv); }

// License: MIT
// Author: Xaychru
// ported by gre from https://gist.github.com/Xaychru/ce1d48f0ce00bb379750

const float smoothness = 1.0;

const float PI = 3.141592653589;

vec4 transition(vec2 p) {
  vec2 rp = p*2.-1.;
  return mix(
    getToColor(p),
    getFromColor(p),
    smoothstep(0., smoothness, atan(rp.y,rp.x) - (progress-.5) * PI * 2.5)
  );
}


void main() {
	gl_FragColor = transition(vUv);
}
`,
			origin: "gl-transitions",
			license: "MIT",
			binaryAssets: false,
			author: "Xaychru",
			sourceFile: "Radial.glsl",
		},
	},
	{
		id: "gl-rectangle",
		name: "Rectangle",
		localizedName: "Rectangle",
		description: "gl-transitions/Rectangle.glsl by martiniti (MIT)",
		defaultDuration: 0.8,
		clip: { type: "shader", easing: "linear" },
		shader: {
			fragmentSource: `
precision highp float;
uniform sampler2D uFrom;
uniform sampler2D uTo;
uniform float uProgress;
uniform float uIntensity;
uniform vec2 uResolution;
varying vec2 vUv;

uniform float uRatio;
#define progress uProgress
#define ratio uRatio
vec4 getFromColor(vec2 uv) { return texture2D(uFrom, uv); }
vec4 getToColor(vec2 uv) { return texture2D(uTo, uv); }

// Author: martiniti
// License: MIT

const vec4 bgcolor = vec4(0.0, 0.0, 0.0, 1.0);

float s = pow(2.0 * abs(progress - 0.5), 3.0);

vec4 transition(vec2 p) {
  
   vec2 sq = p.xy / vec2(1.0).xy;
   
    // bottom-left
    vec2 bl = step(vec2(abs(1. - 2.*progress)), sq + .25);
    float dist = bl.x * bl.y;

    // top-right
    vec2 tr = step(vec2(abs(1. - 2.*progress)), 1.25-sq);
    dist *= 1. * tr.x * tr.y;
  
  return mix(
    progress < 0.5 ? getFromColor(p) : getToColor(p),
    bgcolor,
    step(s, dist)
  );
  
}


void main() {
	gl_FragColor = transition(vUv);
}
`,
			origin: "gl-transitions",
			license: "MIT",
			binaryAssets: false,
			author: "martiniti",
			sourceFile: "Rectangle.glsl",
		},
	},
	{
		id: "gl-rectangle-crop",
		name: "Rectangle Crop",
		localizedName: "Rectangle Crop",
		description: "gl-transitions/RectangleCrop.glsl by martiniti (MIT)",
		defaultDuration: 0.8,
		clip: { type: "shader", easing: "linear" },
		shader: {
			fragmentSource: `
precision highp float;
uniform sampler2D uFrom;
uniform sampler2D uTo;
uniform float uProgress;
uniform float uIntensity;
uniform vec2 uResolution;
varying vec2 vUv;

uniform float uRatio;
#define progress uProgress
#define ratio uRatio
vec4 getFromColor(vec2 uv) { return texture2D(uFrom, uv); }
vec4 getToColor(vec2 uv) { return texture2D(uTo, uv); }

// License: MIT
// Author: martiniti

const vec4 bgcolor = vec4(0.0, 0.0, 0.0, 1.0);

vec4 transition(vec2 uv) {
  
  float s = pow(2.0 * abs(progress - 0.5), 3.0);
              
  vec2 q = uv.xy / vec2(1.0).xy;
  
  // bottom-left
  vec2 bl = step(vec2(1.0 - 2.0*abs(progress - 0.5)), q + 0.25);
  
  // top-right
  vec2 tr = step(vec2(1.0 - 2.0*abs(progress - 0.5)), 1.25 - q);
  
  float dist = length(1.0 - bl.x * bl.y * tr.x * tr.y);
  
  return mix(
    progress < 0.5 ? getFromColor(uv) : getToColor(uv),
    bgcolor,
    step(s, dist)
  );
  
}


void main() {
	gl_FragColor = transition(vUv);
}
`,
			origin: "gl-transitions",
			license: "MIT",
			binaryAssets: false,
			author: "martiniti",
			sourceFile: "RectangleCrop.glsl",
		},
	},
	{
		id: "gl-revolve-left",
		name: "Revolve Left",
		localizedName: "Revolve Left",
		description: "gl-transitions/Revolve_Left.glsl by bread (MIT)",
		defaultDuration: 0.8,
		clip: { type: "shader", easing: "linear" },
		shader: {
			fragmentSource: `
precision highp float;
uniform sampler2D uFrom;
uniform sampler2D uTo;
uniform float uProgress;
uniform float uIntensity;
uniform vec2 uResolution;
varying vec2 vUv;

uniform float uRatio;
#define progress uProgress
#define ratio uRatio
vec4 getFromColor(vec2 uv) { return texture2D(uFrom, uv); }
vec4 getToColor(vec2 uv) { return texture2D(uTo, uv); }

// Author: bread
// License: MIT
// gl-transitions v1 compatible

const vec2 center = vec2(0.46, 0.52);
const float direction = -1.0;
const float maxRotation = 1.95;
const float peakZoom = 2.22;
const float swirl = 2.85;
const float barrel = 0.38;
const float motionBlur = 1.0;
const float switchStart = 0.30;
const float switchEnd = 0.50;
const float shadow = 0.16;

float sat(float x) {
  return clamp(x, 0.0, 1.0);
}

float ease(float x) {
  x = sat(x);
  return x * x * (3.0 - 2.0 * x);
}

float revolveEnvelope(float t) {
  float rise = ease((t - 0.10) / 0.33);
  float fall = 1.0 - ease((t - 0.43) / 0.29);
  return rise * fall;
}

vec2 rotate2(vec2 p, float a) {
  float s = sin(a);
  float c = cos(a);
  return vec2(c * p.x - s * p.y, s * p.x + c * p.y);
}

vec2 warpUv(vec2 uv, float t) {
  float e = revolveEnvelope(t);

  vec2 p = uv - center;
  p.x *= ratio;

  float r = length(p);
  float edgeSpin = maxRotation * e;
  float coreSpin = swirl * e * pow(1.0 - sat(r / 0.96), 1.55);
  float visibleAngle = direction * (edgeSpin + coreSpin);

  p = rotate2(p, -visibleAngle);

  float sc = 1.0 + (peakZoom - 1.0) * pow(e, 0.85);
  p /= sc;

  float rr = length(p);
  p *= 1.0 + barrel * e * rr * rr * 2.8;

  p.x /= ratio;
  return clamp(p + center, vec2(0.001), vec2(0.999));
}

vec4 sampleRevolve(vec2 uv, float t) {
  vec2 p = warpUv(uv, t);
  float reveal = smoothstep(switchStart, switchEnd, t);
  return mix(getFromColor(p), getToColor(p), reveal);
}

vec4 transition(vec2 uv) {
  if (progress <= 0.0) return getFromColor(uv);
  if (progress >= 1.0) return getToColor(uv);

  float e = revolveEnvelope(progress);
  float span = 0.060 * motionBlur * e;

  vec4 color = vec4(0.0);
  float total = 0.0;

  for (int i = -8; i <= 8; i++) {
    float x = float(i) / 8.0;
    float w = 1.0 - abs(x);
    w = w * w + 0.01;

    float t = sat(progress + x * span);
    color += sampleRevolve(uv, t) * w;
    total += w;
  }

  color /= total;

  vec2 q = uv - vec2(0.5);
  q.x *= ratio;
  float vignette = 1.0 - shadow * e * smoothstep(0.35, 0.95, length(q));
  color.rgb *= vignette;

  return color;
}


void main() {
	gl_FragColor = transition(vUv);
}
`,
			origin: "gl-transitions",
			license: "MIT",
			binaryAssets: false,
			author: "bread",
			sourceFile: "Revolve_Left.glsl",
		},
	},
	{
		id: "gl-rolls",
		name: "Rolls",
		localizedName: "Rolls",
		description: "gl-transitions/Rolls.glsl by Mark Craig (MIT)",
		defaultDuration: 0.8,
		clip: { type: "shader", easing: "linear" },
		shader: {
			fragmentSource: `
precision highp float;
uniform sampler2D uFrom;
uniform sampler2D uTo;
uniform float uProgress;
uniform float uIntensity;
uniform vec2 uResolution;
varying vec2 vUv;

uniform float uRatio;
#define progress uProgress
#define ratio uRatio
vec4 getFromColor(vec2 uv) { return texture2D(uFrom, uv); }
vec4 getToColor(vec2 uv) { return texture2D(uTo, uv); }

// Author: Mark Craig
// mrmcsoftware on github and youtube ( http://www.youtube.com/MrMcSoftware )
// License: MIT

// Rolls Transition by Mark Craig (Copyright © 2022)

const int type = 0;
const bool RotDown = false;
// type (0-3): Rotate/Roll from which corner
// RotDown: if true rotate old image down, otherwise rotate old image up

#define M_PI 3.14159265358979323846

vec4 transition(vec2 uv)
{
float theta, c1, s1;
vec2 iResolution = vec2(ratio, 1.0);
vec2 uvi;
// I used if/else instead of switch in case it's an old GPU
if (type == 0) { theta = (RotDown ? M_PI : -M_PI) / 2.0 * progress; uvi.x = 1.0 - uv.x; uvi.y = uv.y; }
else if (type == 1) { theta = (RotDown ? M_PI : -M_PI) / 2.0 * progress; uvi = uv; }
else if (type == 2) { theta = (RotDown ? -M_PI : M_PI) / 2.0 * progress; uvi.x = uv.x; uvi.y = 1.0 - uv.y; }
else if (type == 3) { theta = (RotDown ? -M_PI : M_PI) / 2.0 * progress; uvi = 1.0 - uv; }
c1 = cos(theta); s1 = sin(theta);
vec2 uv2;
uv2.x = (uvi.x * iResolution.x * c1 - uvi.y * iResolution.y * s1);
uv2.y = (uvi.x * iResolution.x * s1 + uvi.y * iResolution.y * c1);
if ((uv2.x >= 0.0) && (uv2.x <= iResolution.x) && (uv2.y >= 0.0) && (uv2.y <= iResolution.y))
	{
	uv2 /= iResolution;
	if (type == 0) { uv2.x = 1.0 - uv2.x; }
	else if (type == 2) { uv2.y = 1.0 - uv2.y; }
	else if (type == 3) { uv2 = 1.0 - uv2; }
	return(getFromColor(uv2));
	}
return(getToColor(uv));
}


void main() {
	gl_FragColor = transition(vUv);
}
`,
			origin: "gl-transitions",
			license: "MIT",
			binaryAssets: false,
			author: "Mark Craig",
			sourceFile: "Rolls.glsl",
		},
	},
];
