// Generated by scripts/import-gl-transitions.ts. Do not edit.
import type { TransitionLabRecipe } from "./transition-lab-catalog.js";
import { GL_TRANSITION_RECIPES_01 } from "./gl-transitions-recipes-01.js";
import { GL_TRANSITION_RECIPES_02 } from "./gl-transitions-recipes-02.js";
import { GL_TRANSITION_RECIPES_03 } from "./gl-transitions-recipes-03.js";
import { GL_TRANSITION_RECIPES_04 } from "./gl-transitions-recipes-04.js";
import { GL_TRANSITION_RECIPES_05 } from "./gl-transitions-recipes-05.js";
import { GL_TRANSITION_RECIPES_06 } from "./gl-transitions-recipes-06.js";
import { GL_TRANSITION_RECIPES_07 } from "./gl-transitions-recipes-07.js";
import { GL_TRANSITION_RECIPES_08 } from "./gl-transitions-recipes-08.js";
import { GL_TRANSITION_RECIPES_09 } from "./gl-transitions-recipes-09.js";
import { GL_TRANSITION_RECIPES_10 } from "./gl-transitions-recipes-10.js";
import { GL_TRANSITION_RECIPES_11 } from "./gl-transitions-recipes-11.js";
import { GL_TRANSITION_RECIPES_12 } from "./gl-transitions-recipes-12.js";
import { GL_TRANSITION_RECIPES_13 } from "./gl-transitions-recipes-13.js";
import { GL_TRANSITION_RECIPES_14 } from "./gl-transitions-recipes-14.js";
import { GL_TRANSITION_RECIPES_15 } from "./gl-transitions-recipes-15.js";
import { GL_TRANSITION_RECIPES_16 } from "./gl-transitions-recipes-16.js";

export const GL_TRANSITIONS_COMMIT = "902218a1b63773ac0d0d9f491951da3392365bfe";

export const GL_TRANSITION_RECIPES: TransitionLabRecipe[] = [
	...GL_TRANSITION_RECIPES_01,
	...GL_TRANSITION_RECIPES_02,
	...GL_TRANSITION_RECIPES_03,
	...GL_TRANSITION_RECIPES_04,
	...GL_TRANSITION_RECIPES_05,
	...GL_TRANSITION_RECIPES_06,
	...GL_TRANSITION_RECIPES_07,
	...GL_TRANSITION_RECIPES_08,
	...GL_TRANSITION_RECIPES_09,
	...GL_TRANSITION_RECIPES_10,
	...GL_TRANSITION_RECIPES_11,
	...GL_TRANSITION_RECIPES_12,
	...GL_TRANSITION_RECIPES_13,
	...GL_TRANSITION_RECIPES_14,
	...GL_TRANSITION_RECIPES_15,
	...GL_TRANSITION_RECIPES_16,
];
